// src/workspace/FileTreeItem.tsx
import { useEffect, useRef, useState, type KeyboardEvent, type MouseEvent } from 'react'
import type { WorkspaceFileEntry } from './workspaceModel'
import { validateItemName } from './workspaceModel'

interface Props {
  entry: WorkspaceFileEntry
  level: number
  expanded: boolean
  isExpanded: (path: string) => boolean
  activePath: string | null
  renamePath: string | null
  draggingPath: string | null
  dropTargetPath: string | null
  onToggle: (path: string) => void
  onSelect: (entry: WorkspaceFileEntry) => void
  onRename: (path: string, name: string) => Promise<boolean>
  onRenameRequest: (path: string) => void
  onContextMenu: (event: MouseEvent, entry: WorkspaceFileEntry) => void
  onPointerDragStart: (event: MouseEvent, path: string) => void
}

export function FileTreeItem({ entry, level, expanded, isExpanded, activePath, renamePath, draggingPath, dropTargetPath, onToggle, onSelect, onRename, onRenameRequest, onContextMenu, onPointerDragStart }: Props) {
  const [renaming, setRenaming] = useState(false)
  const [value, setValue] = useState(entry.name)
  const inputRef = useRef<HTMLInputElement>(null)
  const renameSubmittingRef = useRef(false)
  useEffect(() => {
    if (renamePath === entry.path) { renameSubmittingRef.current = false; setRenaming(true) }
  }, [entry.path, renamePath])
  useEffect(() => { if (renaming) { inputRef.current?.focus(); inputRef.current?.select() } }, [renaming])

  const finishRename = async () => {
    if (renameSubmittingRef.current) return
    renameSubmittingRef.current = true
    const name = value.trim()
    if (!name || name === entry.name) { setRenaming(false); renameSubmittingRef.current = false; return }
    if (validateItemName(name)) { await onRename(entry.path, name) }
    setRenaming(false)
    renameSubmittingRef.current = false
  }
  const keyDown = (event: KeyboardEvent<HTMLDivElement>) => {
    if (renaming) return
    if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); onSelect(entry) }
    else if (event.key === 'ArrowRight' && entry.is_dir && !expanded) { event.preventDefault(); onToggle(entry.path) }
    else if (event.key === 'ArrowLeft' && entry.is_dir && expanded) { event.preventDefault(); onToggle(entry.path) }
    else if (event.key === 'F2') { event.preventDefault(); setValue(entry.name); onRenameRequest(entry.path) }
  }
  const dragStart = (event: MouseEvent<HTMLDivElement>) => {
    if (renaming || (event.target as HTMLElement).closest('button,input')) return
    onPointerDragStart(event, entry.path)
  }
  const isActive = activePath === entry.path
  const isOther = !entry.is_dir && !entry.is_markdown
  const iconClass = `pi react-tree-icon flex-none text-sm ${entry.is_dir || entry.is_markdown ? 'text-[rgb(var(--react-brand-rgb))]' : 'text-white/60'}`
  const itemClass = `flex w-full min-w-0 min-h-0 cursor-pointer items-center gap-1 rounded px-2 py-1 text-left text-white/80 transition-[background] duration-100 hover:bg-white/[0.08] hover:text-white${isActive ? ' bg-[rgba(var(--react-brand-rgb),0.3)] text-white hover:bg-[rgba(var(--react-brand-rgb),0.3)]' : ''}${isOther && !isActive ? ' opacity-50' : ''}${draggingPath === entry.path ? ' opacity-[.45]' : ''}${dropTargetPath === entry.path ? ' bg-[rgba(var(--react-brand-rgb),0.22)] shadow-[inset_0_0_0_1px_rgba(var(--react-brand-rgb),0.7)]' : ''}`
  return <li role="none">
    <div
        className={itemClass}
       style={{ paddingLeft: `${level * 16}px` }} role="treeitem" tabIndex={0} aria-level={level + 1}
       aria-expanded={entry.is_dir ? expanded : undefined} aria-selected={activePath === entry.path}
       data-entry-path={entry.path} data-entry-dir={entry.is_dir ? 'true' : 'false'}
       onKeyDown={keyDown} onClick={() => !renaming && onSelect(entry)} onContextMenu={event => onContextMenu(event, entry)}
       onDoubleClick={() => { if (!entry.is_dir) { setValue(entry.name); onRenameRequest(entry.path) } }} onMouseDown={dragStart}
    >
       {entry.is_dir ? <button type="button" className="inline-flex h-[18px] w-[18px] flex-none cursor-pointer items-center justify-center rounded-[3px] border-0 bg-transparent p-0 text-inherit hover:bg-white/10" aria-label={expanded ? `Collapse ${entry.name}` : `Expand ${entry.name}`} aria-expanded={expanded} onClick={event => { event.stopPropagation(); onToggle(entry.path) }}><i className={`pi ${expanded ? 'pi-chevron-down' : 'pi-chevron-right'} text-[10px]`} aria-hidden="true" /></button> : <span className="inline-flex h-[18px] w-[18px] flex-none" />}
        <i className={`${iconClass} ${entry.is_dir ? (expanded ? 'pi-folder-open' : 'pi-folder') : 'pi-file'}`} aria-hidden="true" />
       {renaming ? <input ref={inputRef} className="min-w-0 flex-1 rounded-[3px] border border-[rgb(var(--react-brand-rgb))] bg-[rgba(0,0,0,0.3)] px-1 py-0.5 text-inherit text-sm text-white outline-none" value={value} aria-label={`Rename ${entry.name}`} onChange={event => setValue(event.target.value)} onBlur={() => void finishRename()} onClick={event => event.stopPropagation()} onKeyDown={event => { event.stopPropagation(); if (event.key === 'Enter') void finishRename(); if (event.key === 'Escape') setRenaming(false) }} /> : <span className="min-w-0 flex-1 overflow-hidden text-ellipsis whitespace-nowrap">{entry.name}</span>}
    </div>
      {entry.is_dir && expanded && entry.children && <ul className="m-0 list-none p-0" role="group">{entry.children.map(child => <FileTreeItem key={child.path} {...{ ...({ entry: child, level: level + 1, expanded: isExpanded(child.path), isExpanded, activePath, renamePath, draggingPath, dropTargetPath, onToggle, onSelect, onRename, onRenameRequest, onContextMenu, onPointerDragStart } as Props) }} />)}</ul>}
  </li>
}

// src/components/sidebar/FileTreeItem.vue
<script setup lang="ts">
import { ref, computed, nextTick } from 'vue'
import { useWorkspaceStore, type FileEntry } from '../../stores/workspaceStore'

const props = defineProps<{
  entry: FileEntry
  level: number
  isExpanded: boolean
  activePath: string | null
}>()

const emit = defineEmits<{
  (e: 'click', entry: FileEntry): void
  (e: 'context-menu', event: MouseEvent, entry: FileEntry): void
  (e: 'toggle', path: string): void
}>()

const workspaceStore = useWorkspaceStore()

const isRenaming = ref(false)
const renameValue = ref('')
const renameInput = ref<HTMLInputElement | null>(null)

const isActive = computed(() => props.activePath === props.entry.path)

const indent = computed(() => `${props.level * 1}rem`)

const icon = computed(() => {
  if (props.entry.is_dir) {
    return props.isExpanded ? 'pi-folder-open' : 'pi-folder'
  }
  if (props.entry.is_markdown) {
    return 'pi-file'
  }
  return 'pi-file'
})

const itemClass = computed(() => ({
  'tree-item': true,
  'is-dir': props.entry.is_dir,
  'is-markdown': props.entry.is_markdown,
  'is-other': !props.entry.is_dir && !props.entry.is_markdown,
  'is-active': isActive.value,
  'is-expanded': props.isExpanded,
}))

function handleClick(_event: MouseEvent) {
  if (isRenaming.value) return
  emit('click', props.entry)
}

function handleContextMenu(event: MouseEvent) {
  emit('context-menu', event, props.entry)
}

function handleToggle(event: MouseEvent) {
  event.stopPropagation()
  emit('toggle', props.entry.path)
}

async function startRename() {
  isRenaming.value = true
  renameValue.value = props.entry.name
  await nextTick()
  renameInput.value?.focus()
  renameInput.value?.select()
}

async function confirmRename() {
  if (!renameValue.value.trim() || renameValue.value === props.entry.name) {
    cancelRename()
    return
  }

  try {
    await workspaceStore.renameItem(props.entry.path, renameValue.value.trim())
  } catch (error) {
    console.error('Failed to rename:', error)
  }

  cancelRename()
}

function cancelRename() {
  isRenaming.value = false
  renameValue.value = ''
}

function handleKeydown(event: KeyboardEvent) {
  if (event.key === 'Enter') {
    confirmRename()
  } else if (event.key === 'Escape') {
    cancelRename()
  }
}

// Expose startRename for parent to call
defineExpose({ startRename })
</script>

<template>
  <li role="none">
    <div
      :class="itemClass"
      :style="{ paddingLeft: indent }"
      @click="handleClick"
      @contextmenu="handleContextMenu"
      @dblclick="entry.is_dir ? null : startRename()"
    >
      <!-- Expand/collapse toggle for directories -->
      <button
        v-if="entry.is_dir"
        class="toggle-btn"
        @click="handleToggle"
        :aria-expanded="isExpanded"
      >
        <i class="pi" :class="isExpanded ? 'pi-chevron-down' : 'pi-chevron-right'"></i>
      </button>
      <span v-else class="toggle-spacer"></span>

      <!-- Icon -->
      <i class="pi item-icon" :class="icon"></i>

      <!-- Name or rename input -->
      <input
        v-if="isRenaming"
        ref="renameInput"
        v-model="renameValue"
        type="text"
        class="rename-input"
        @blur="confirmRename"
        @keydown="handleKeydown"
        @click.stop
      />
      <span v-else class="item-name">{{ entry.name }}</span>
    </div>

    <!-- Children (for directories) -->
    <ul
      v-if="entry.is_dir && entry.children && isExpanded"
      class="tree-children"
      role="group"
    >
      <FileTreeItem
        v-for="child in entry.children"
        :key="child.path"
        :entry="child"
        :level="level + 1"
        :is-expanded="workspaceStore.isExpanded(child.path)"
        :active-path="activePath"
        @click="emit('click', $event)"
        @context-menu="emit('context-menu', $event, child)"
        @toggle="emit('toggle', $event)"
      />
    </ul>
  </li>
</template>

<style scoped>
.tree-item {
  display: flex;
  align-items: center;
  gap: 0.25rem;
  padding: 0.25rem 0.5rem;
  cursor: pointer;
  border-radius: 4px;
  color: rgba(255, 255, 255, 0.8);
  transition: background 0.1s;
}

.tree-item:hover {
  background: rgba(255, 255, 255, 0.08);
}

.tree-item.is-active {
  background: rgba(var(--tt-brand-color-rgb, 98, 41, 255), 0.3);
  color: white;
}

.tree-item.is-other {
  opacity: 0.5;
}

.toggle-btn {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 18px;
  height: 18px;
  padding: 0;
  background: none;
  border: none;
  color: inherit;
  cursor: pointer;
  border-radius: 3px;
  flex-shrink: 0;
}

.toggle-btn:hover {
  background: rgba(255, 255, 255, 0.1);
}

.toggle-btn .pi {
  font-size: 0.625rem;
}

.toggle-spacer {
  width: 18px;
  flex-shrink: 0;
}

.item-icon {
  font-size: 0.875rem;
  flex-shrink: 0;
  color: rgba(255, 255, 255, 0.6);
}

.is-dir .item-icon {
  color: #ffd43b;
}

.is-markdown .item-icon {
  color: var(--tt-brand-color-500);
}

.item-name {
  flex: 1;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}

.rename-input {
  flex: 1;
  padding: 0.125rem 0.25rem;
  background: rgba(0, 0, 0, 0.3);
  border: 1px solid var(--tt-brand-color-500);
  border-radius: 3px;
  color: white;
  font-size: inherit;
  min-width: 0;
}

.rename-input:focus {
  outline: none;
}

.tree-children {
  list-style: none;
  margin: 0;
  padding: 0;
}
</style>
